name: Pack
on: workflow_dispatch
jobs:
  pack-to-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true
      - name: Install dependencies
        run: sudo apt -y install findutils zip unzip
      - name: Delete unused files
        run: |
          cd "$GITHUB_WORKSPACE"
          echo $(($(git log -1 --format=%ct) * 1000)) > .commit_time
          cd ..
          zip -9 -r -v "$RUNNER_TEMP/mpv-config".zip mpv-config
          zip -d -v "$RUNNER_TEMP/mpv-config.zip" \*.git\* mpv-config/git-modules\*
          unzip -d "$RUNNER_TEMP" "$RUNNER_TEMP/mpv-config.zip"
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: mpv-config
          path: ${{ runner.temp }}/mpv-config
